import { CryptoName } from "src/app/types/cryptoName.type";

export const cryptoNames: CryptoName[] = [
    new CryptoName("Bitcoin","BTC", 1),
    new CryptoName("Cardano","ADA", 2010),
    new CryptoName("Litecoin","LTE", 2),
    new CryptoName("Ethereum","ETH", 1027),
    new CryptoName("Polkadot","DOT", 6636),
    new CryptoName("Stella","XLM", 512),
    new CryptoName("Tether","USDT", 825),
    new CryptoName("XRP","XRP", 742),
    new CryptoName("Solana","SOL", 5426)
  ]

  export const twelveHoursInMs: number = 43200000;
  export const SORT_MODE_STORAGE_KEY: string = "sortMode";
  export const CURRENCY_SELECTED_STORAGE_KEY: string = "currencySelected";

  /* export const cryptoNames: CryptoName[] = [
    { displayName: "Bitcoin", ticker: "BTC" },
    { displayName: "Cardano", ticker: "ADA" },
    { displayName: "Litecoin", ticker: "LTC" },
    { displayName: "Ethereum", ticker: "ETH" },
    { displayName: "Polkadot", ticker: "DOT" },
    { displayName: "Stellar", ticker: "XLM" },
    { displayName: "Tether", ticker: "USDT" },
    { displayName: "XRP", ticker: "XRP" },
    { displayName: "Solana", ticker: "SOL" }
]; */

export interface CoinDetails {
  displayName: string;
  ticker: string;
}

export const cryptoNamesMap: Map<number, CoinDetails> = new Map([
  [1, { displayName: "Bitcoin", ticker: "BTC" }],
  [2, { displayName: "Litecoin", ticker: "LTC" }],
  [52, { displayName: "XRP", ticker: "XRP" }],
  [74, { displayName: "Dogecoin", ticker: "DOGE" }],
  [109, { displayName: "DigiByte", ticker: "DGB" }],
  [131, { displayName: "Dash", ticker: "DASH" }],
  [328, { displayName: "Monero", ticker: "XMR" }],
  [512, { displayName: "Stellar", ticker: "XLM" }],
  [825, { displayName: "Tether USDt", ticker: "USDT" }],
  [873, { displayName: "NEM", ticker: "XEM" }],
  [1027, { displayName: "Ethereum", ticker: "ETH" }],
  [1042, { displayName: "Siacoin", ticker: "SC" }],
  [1168, { displayName: "Decred", ticker: "DCR" }],
  [1214, { displayName: "Lisk", ticker: "LSK" }],
  [1274, { displayName: "Waves", ticker: "WAVES" }],
  [1321, { displayName: "Ethereum Classic", ticker: "ETC" }],
  [1343, { displayName: "Stratis", ticker: "STRAX" }],
  [1376, { displayName: "Neo", ticker: "NEO" }],
  [1437, { displayName: "Zcash", ticker: "ZEC" }],
  [1455, { displayName: "Golem", ticker: "GLM" }],
  [1518, { displayName: "Maker", ticker: "MKR" }],
  [1586, { displayName: "Ark", ticker: "ARK" }],
  [1659, { displayName: "Gnosis", ticker: "GNO" }],
  [1680, { displayName: "Aragon", ticker: "ANT" }],
  [1684, { displayName: "Qtum", ticker: "QTUM" }],
  [1697, { displayName: "Basic Attention Token", ticker: "BAT" }],
  [1698, { displayName: "Horizen", ticker: "ZEN" }],
  [1720, { displayName: "IOTA", ticker: "IOTA" }],
  [1759, { displayName: "Status", ticker: "SNT" }],
  [1765, { displayName: "EOS", ticker: "EOS" }],
  [1772, { displayName: "Storj", ticker: "STORJ" }],
  [1785, { displayName: "Gas", ticker: "GAS" }],
  [1831, { displayName: "Bitcoin Cash", ticker: "BCH" }],
  [1839, { displayName: "BNB", ticker: "BNB" }],
  [1896, { displayName: "0x Protocol", ticker: "ZRX" }],
  [1934, { displayName: "Loopring", ticker: "LRC" }],
  [1958, { displayName: "TRON", ticker: "TRX" }],
  [1966, { displayName: "Decentraland", ticker: "MANA" }],
  [1975, { displayName: "Chainlink", ticker: "LINK" }],
  [2010, { displayName: "Cardano", ticker: "ADA" }],
  [2011, { displayName: "Tezos", ticker: "XTZ" }],
  [2083, { displayName: "Bitcoin Gold", ticker: "BTG" }],
  [2087, { displayName: "KuCoin Token", ticker: "KCS" }],
  [2099, { displayName: "ICON", ticker: "ICX" }],
  [2130, { displayName: "Enjin Coin", ticker: "ENJ" }],
  [2280, { displayName: "Filecoin", ticker: "FIL" }],
  [2299, { displayName: "aelf", ticker: "ELF" }],
  [2300, { displayName: "WAX", ticker: "WAXP" }],
  [2405, { displayName: "IOST", ticker: "IOST" }],
  [2416, { displayName: "Theta Network", ticker: "THETA" }],
  [2424, { displayName: "SingularityNET", ticker: "AGIX" }],
  [2454, { displayName: "UnlimitedIP", ticker: "UIP" }],
  [2469, { displayName: "Zilliqa", ticker: "ZIL" }],
  [2496, { displayName: "Polymath", ticker: "POLY" }],
  [2499, { displayName: "SwissBorg", ticker: "BORG" }],
  [2502, { displayName: "Huobi Token", ticker: "HT" }],
  [2502, { displayName: "Huobi Token", ticker: "HT" }],
  [2563, { displayName: "TrueUSD", ticker: "TUSD" }],
  [2566, { displayName: "Ontology", ticker: "ONT" }],
  [2577, { displayName: "Ravencoin", ticker: "RVN" }],
  [2586, { displayName: "Synthetix", ticker: "SNX" }],
  [2588, { displayName: "Loom Network", ticker: "LOOM" }],
  [2634, { displayName: "XDC Network", ticker: "XDC" }],
  [2682, { displayName: "Holo", ticker: "HOT" }],
  [2694, { displayName: "Nexo", ticker: "NEXO" }],
  [2777, { displayName: "IoTeX", ticker: "IOTX" }],
  [2943, { displayName: "Rocket Pool", ticker: "RPL" }],
  [3029, { displayName: "Flux", ticker: "FLUX" }],
  [3077, { displayName: "VeChain", ticker: "VET" }],
  [3155, { displayName: "Quant", ticker: "QNT" }],
  [3306, { displayName: "Gemini Dollar", ticker: "GUSD" }],
  [3330, { displayName: "Pax Dollar", ticker: "USDP" }],
  [3408, { displayName: "USDC", ticker: "USDC" }],
  [3513, { displayName: "Fantom", ticker: "FTM" }],
  [3602, { displayName: "Bitcoin SV", ticker: "BSV" }],
  [3635, { displayName: "Cronos", ticker: "CRO" }],
  [3640, { displayName: "Livepeer", ticker: "LPT" }],
  [3717, { displayName: "Wrapped Bitcoin", ticker: "WBTC" }],
  [3718, { displayName: "BitTorrent", ticker: "BTTOLD" }],
  [3773, { displayName: "Fetch.ai", ticker: "FET" }],
  [3783, { displayName: "Ankr", ticker: "ANKR" }],
  [3794, { displayName: "Cosmos", ticker: "ATOM" }],
  [3801, { displayName: "BORA", ticker: "BORA" }],
  [3822, { displayName: "Theta Fuel", ticker: "TFUEL" }],
  [3835, { displayName: "Orbs", ticker: "ORBS" }],
  [3890, { displayName: "Polygon", ticker: "MATIC" }],
  [3897, { displayName: "OKB", ticker: "OKB" }],
  [3911, { displayName: "Ocean Protocol", ticker: "OCEAN" }],
  [3945, { displayName: "Harmony", ticker: "ONE" }],
  [3957, { displayName: "UNUS SED LEO", ticker: "LEO" }],
  [3987, { displayName: "Beldex", ticker: "BDX" }],
  [4006, { displayName: "STP", ticker: "STPT" }],
  [4023, { displayName: "Bitcoin BEP2", ticker: "BTCB" }],
  [4030, { displayName: "Algorand", ticker: "ALGO" }],
  [4041, { displayName: "MX TOKEN", ticker: "MX" }],
  [4066, { displayName: "Chiliz", ticker: "CHZ" }],
  [4157, { displayName: "THORChain", ticker: "RUNE" }],
  [4172, { displayName: "Terra Classic", ticker: "LUNC" }],
  [4195, { displayName: "FTX Token", ticker: "FTT" }],
  [4256, { displayName: "Klaytn", ticker: "KLAY" }],
  [4269, { displayName: "GateToken", ticker: "GT" }],
  [4279, { displayName: "Solar", ticker: "SXP" }],
  [4512, { displayName: "FINSCHIA", ticker: "FNSA" }],
  [4512, { displayName: "FINSCHIA", ticker: "FNSA" }],
  [4558, { displayName: "Flow", ticker: "FLOW" }],
  [4642, { displayName: "Hedera", ticker: "HBAR" }],
  [4679, { displayName: "Band Protocol", ticker: "BAND" }],
  [4687, { displayName: "BUSD", ticker: "BUSD" }],
  [4705, { displayName: "PAX Gold", ticker: "PAXG" }],
  [4846, { displayName: "Kava", ticker: "KAVA" }],
  [4847, { displayName: "Stacks", ticker: "STX" }],
  [4943, { displayName: "Dai", ticker: "DAI" }],
  [4944, { displayName: "Tellor", ticker: "TRB" }],
  [4948, { displayName: "Nervos Network", ticker: "CKB" }],
  [5015, { displayName: "HEX", ticker: "HEX" }],
  [5034, { displayName: "Kusama", ticker: "KSM" }],
  [5168, { displayName: "Bitcoin Classic", ticker: "BXC" }],
  [5176, { displayName: "Tether Gold", ticker: "XAUt" }],
  [5190, { displayName: "FLEX", ticker: "FLEX" }],
  [5370, { displayName: "Hive", ticker: "HIVE" }],
  [5426, { displayName: "Solana", ticker: "SOL" }],
  [5446, { displayName: "USDJ", ticker: "USDJ" }],
  [5455, { displayName: "Trexcoin", ticker: "TREX" }],
  [5488, { displayName: "JUST", ticker: "JST" }],
  [5524, { displayName: "TNC Coin", ticker: "TNC" }],
  [5567, { displayName: "Celo", ticker: "CELO" }],
  [5617, { displayName: "UMA", ticker: "UMA" }],
  [5632, { displayName: "Arweave", ticker: "AR" }],
  [5647, { displayName: "Kadena", ticker: "KDA" }],
  [5665, { displayName: "Helium", ticker: "HNT" }],
  [5690, { displayName: "Render", ticker: "RNDR" }],
  [5691, { displayName: "SKALE", ticker: "SKL" }],
  [5692, { displayName: "Compound", ticker: "COMP" }],
  [5728, { displayName: "Balancer", ticker: "BAL" }],
  [5804, { displayName: "DeFiChain", ticker: "DFI" }],
  [5805, { displayName: "Avalanche", ticker: "AVAX" }],
  [5864, { displayName: "yearn.finance", ticker: "YFI" }],
  [5899, { displayName: "Casper", ticker: "CSPR" }],
  [5964, { displayName: "Trust Wallet Token", ticker: "TWT" }],
  [5994, { displayName: "Shiba Inu", ticker: "SHIB" }],
  [6210, { displayName: "The Sandbox", ticker: "SAND" }],
  [6535, { displayName: "NEAR Protocol", ticker: "NEAR" }],
  [6535, { displayName: "NEAR Protocol", ticker: "NEAR" }],
  [6538, { displayName: "Curve DAO Token", ticker: "CRV" }],
  [6538, { displayName: "Curve DAO Token", ticker: "CRV" }],
  [6636, { displayName: "Polkadot", ticker: "DOT" }],
  [6719, { displayName: "The Graph", ticker: "GRT" }],
  [6748, { displayName: "Centrifuge", ticker: "CFG" }],
  [6758, { displayName: "SushiSwap", ticker: "SUSHI" }],
  [6783, { displayName: "Axie Infinity", ticker: "AXS" }],
  [6836, { displayName: "Moonbeam", ticker: "GLMR" }],
  [6892, { displayName: "MultiversX", ticker: "EGLD" }],
  [6941, { displayName: "Huobi BTC", ticker: "HBTC" }],
  [6952, { displayName: "Frax", ticker: "FRAX" }],
  [6953, { displayName: "Frax Share", ticker: "FXS" }],
  [6958, { displayName: "Alchemy Pay", ticker: "ACH" }],
  [7080, { displayName: "Gala", ticker: "GALA" }],
  [7083, { displayName: "Uniswap", ticker: "UNI" }],
  [7186, { displayName: "PancakeSwap", ticker: "CAKE" }],
  [7192, { displayName: "Wrapped BNB", ticker: "WBNB" }],
  [7226, { displayName: "Injective", ticker: "INJ" }],
  [7278, { displayName: "Aave", ticker: "AAVE" }],
  [7326, { displayName: "DeXe", ticker: "DEXE" }],
  [7334, { displayName: "Conflux", ticker: "CFX" }],
  [7429, { displayName: "Liquity", ticker: "LQTY" }],
  [7431, { displayName: "Akash Network", ticker: "AKT" }],
  [7455, { displayName: "Audius", ticker: "AUDIO" }],
  [7501, { displayName: "WOO Network", ticker: "WOO" }],
  [7501, { displayName: "WOO Network", ticker: "WOO" }],
  [7548, { displayName: "WEMIX", ticker: "WEMIX" }],
  [7653, { displayName: "Oasis Network", ticker: "ROSE" }],
  [7950, { displayName: "Flare", ticker: "FLR" }],
  [7961, { displayName: "Venus BNB", ticker: "vBNB" }],
  [8000, { displayName: "Lido DAO", ticker: "LDO" }],
  [8000, { displayName: "Lido DAO", ticker: "LDO" }],
  [8085, { displayName: "Lido Staked ETH", ticker: "stETH" }],
  [8104, { displayName: "1inch Network", ticker: "1INCH" }],
  [8119, { displayName: "SafePal", ticker: "SFP" }],
  [8425, { displayName: "JasmyCoin", ticker: "JASMY" }],
  [8536, { displayName: "Mask Network", ticker: "MASK" }],
  [8646, { displayName: "Mina", ticker: "MINA" }],
  [8719, { displayName: "Illuvium", ticker: "ILV" }],
  [8916, { displayName: "Internet Computer", ticker: "ICP" }],
  [9040, { displayName: "Pundi X (New)", ticker: "PUNDIX" }],
  [9258, { displayName: "Chia", ticker: "XCH" }],
  [9308, { displayName: "Vulcan Forged PYR", ticker: "PYR" }],
  [9466, { displayName: "Edgecoin", ticker: "EDGT" }],
  [9481, { displayName: "Pendle", ticker: "PENDLE" }],
  [9543, { displayName: "Biconomy", ticker: "BICO" }],
  [9566, { displayName: "Liquity USD", ticker: "LUSD" }],
  [9816, { displayName: "APENFT", ticker: "NFT" }],
  [9903, { displayName: "Convex Finance", ticker: "CVX" }],
  [10407, { displayName: "Baby Doge Coin", ticker: "BabyDoge" }],
  [10603, { displayName: "Immutable", ticker: "IMX" }],
  [10791, { displayName: "eCash", ticker: "XEC" }],
  [10804, { displayName: "FLOKI", ticker: "FLOKI" }],
  [11092, { displayName: "Bitget Token", ticker: "BGB" }],
  [11156, { displayName: "dYdX (ethDYDX)", ticker: "ETHDYDX" }],
  [11419, { displayName: "Toncoin", ticker: "TON" }],
  [11840, { displayName: "Optimism", ticker: "OP" }],
  [11841, { displayName: "Arbitrum", ticker: "ARB" }],
  [11857, { displayName: "GMX", ticker: "GMX" }],
  [11865, { displayName: "Bone ShibaSwap", ticker: "BONE" }],
  [11877, { displayName: "Galxe", ticker: "GAL" }],
  [11948, { displayName: "Radix", ticker: "XRD" }],
  [11976, { displayName: "Aleph Zero", ticker: "AZERO" }],
  [12220, { displayName: "Osmosis", ticker: "OSMO" }],
  [12885, { displayName: "Astar", ticker: "ASTR" }],
  [12999, { displayName: "ssv.network", ticker: "SSV" }],
  [13502, { displayName: "Worldcoin", ticker: "WLD" }],
  [13502, { displayName: "Worldcoin", ticker: "WLD" }],
  [13855, { displayName: "Ethereum Name Service", ticker: "ENS" }],
  [14101, { displayName: "Ronin", ticker: "RON" }],
  [14783, { displayName: "Magic", ticker: "MAGIC" }],
  [15185, { displayName: "Kujira", ticker: "KUJI" }],
  [15271, { displayName: "Rollbit Coin", ticker: "RLB" }],
  [16086, { displayName: "BitTorrent(New)", ticker: "BTT" }],
  [17520, { displayName: "Orbler", ticker: "ORBR" }],
  [17520, { displayName: "Orbler", ticker: "ORBR" }],
  [17751, { displayName: "Threshold", ticker: "T" }],
  [17799, { displayName: "Axelar", ticker: "AXL" }],
  [18069, { displayName: "STEPN", ticker: "GMT" }],
  [18579, { displayName: "Wrapped TRON", ticker: "WTRX" }],
  [18876, { displayName: "ApeCoin", ticker: "APE" }],
  [19891, { displayName: "USDD", ticker: "USDD" }],
  [20314, { displayName: "Terra", ticker: "LUNA" }],
  [20362, { displayName: "Polymesh", ticker: "POLYX" }],
  [20396, { displayName: "Kaspa", ticker: "KAS" }],
  [20947, { displayName: "Sui", ticker: "SUI" }],
  [21296, { displayName: "EthereumPoW", ticker: "ETHW" }],
  [21794, { displayName: "Aptos", ticker: "APT" }],
  [22615, { displayName: "Fasttoken", ticker: "FTN" }],
  [22861, { displayName: "Celestia", ticker: "TIA" }],
  [23054, { displayName: "Cheelee", ticker: "CHEEL" }],
  [23054, { displayName: "Cheelee", ticker: "CHEEL" }],
  [23121, { displayName: "Blur", ticker: "BLUR" }],
  [23149, { displayName: "Sei", ticker: "SEI" }],
  [23246, { displayName: "tomiNet", ticker: "TOMI" }],
  [24165, { displayName: "Wrapped Kava", ticker: "WKAVA" }],
  [24399, { displayName: "Wrapped HBAR", ticker: "WHBAR" }],
  [24478, { displayName: "Pepe", ticker: "PEPE" }],
  [24760, { displayName: "Wrapped Beacon ETH", ticker: "WBETH" }],
  [24913, { displayName: "Wrapped EOS", ticker: "WEOS" }],
  [25028, { displayName: "ORDI", ticker: "ORDI" }],
  [25028, { displayName: "ORDI", ticker: "ORDI" }],
  [26081, { displayName: "First Digital USD", ticker: "FDUSD" }],
  [27075, { displayName: "Mantle", ticker: "MNT" }],
  [27622, { displayName: "LUKSO", ticker: "LYX" }],
  [27966, { displayName: "Dora Factory", ticker: "DORA" }],
  [28301, { displayName: "Memecoin", ticker: "MEME" }]
]);